package com.sequenceiq.cloudbreak.api.model;

public enum DetailedStackStatus {
    UNKNOWN,
    PROVISION_REQUESTED,
    PROVISION_SETUP,
    PROVISION_SETUP_FINISHED,
    IMAGE_SETUP,
    IMAGE_SETUP_FINISHED,
    CREATING_INFRASTRUCTURE,
    INFRASTRUCTURECREATION_FINISHED,
    METADATA_COLLECTION,
    METADATA_COLLECTION_FINISHED,
    TLS_SETUP,
    TLS_SETUP_FINISHED,
    PROVISIONED
}
